"""back

Revision ID: 257484e02be5
Revises: 51aca5adcdb9
Create Date: 2025-05-13 17:44:17.616493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257484e02be5'
down_revision: Union[str, None] = '51aca5adcdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_telegram_username_key', 'admins', type_='unique')
    op.drop_column('admins', 'telegram_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('telegram_username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('admins_telegram_username_key', 'admins', ['telegram_username'])
    # ### end Alembic commands ###
