"""rename order

Revision ID: 323fa492c37a
Revises: 11f77a6fbd96
Create Date: 2025-05-08 14:52:28.017741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323fa492c37a'
down_revision: Union[str, None] = '11f77a6fbd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fullname', sa.String(length=150), nullable=True))
    op.drop_column('orders', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('orders', 'fullname')
    # ### end Alembic commands ###
