"""add telegram nickname

Revision ID: 51aca5adcdb9
Revises: 8c1184bed3f9
Create Date: 2025-05-13 17:31:44.406080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51aca5adcdb9'
down_revision: Union[str, None] = '8c1184bed3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('telegram_username', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'admins', ['telegram_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'telegram_username')
    # ### end Alembic commands ###
