"""add admin username unique

Revision ID: 62ef0c9189bf
Revises: af482cb31c66
Create Date: 2025-05-01 16:31:59.103968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ef0c9189bf'
down_revision: Union[str, None] = 'af482cb31c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
