"""init

Revision ID: 81756eb9dccf
Revises: 
Create Date: 2025-04-30 19:07:27.680472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81756eb9dccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('model_type', sa.String(length=150), nullable=True),
    sa.Column('status', postgresql.ENUM('В очереди', 'В работе', 'Готов к выдаче', 'Выполнен', 'Отменен', 'Не выполнен', name='order_status_enum'), nullable=False),
    sa.Column('price_estimate', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('expectation_date', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('master', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('photos_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_table('orders')
    # ### end Alembic commands ###
