"""order add master_id

Revision ID: 8c1184bed3f9
Revises: c93b93f2749d
Create Date: 2025-05-11 15:38:17.233945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1184bed3f9'
down_revision: Union[str, None] = 'c93b93f2749d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('master_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'admins', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'master_id')
    # ### end Alembic commands ###
