"""add admin phone

Revision ID: af482cb31c66
Revises: 51cfa0e99116
Create Date: 2025-05-01 16:24:46.157655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af482cb31c66"
down_revision: Union[str, None] = "51cfa0e99116"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins", "phone", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins", "phone", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###
