"""FK order to admin

Revision ID: c93b93f2749d
Revises: 323fa492c37a
Create Date: 2025-05-11 15:32:21.211319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93b93f2749d'
down_revision: Union[str, None] = '323fa492c37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('master', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
